### ISSUE TITLE
ValueError: Discrete training for subVPSDE is not recommended

### ISSUE THREAD

**Issue by hanlaoshi** [yantijin/ScoreGradPred#2]
Hi, I encountered with an issue "ValueError: Discrete training for subVPSDE is not recommended" when i used my self dataset and setted the md_type=''subvpsde'. What shuold i do to solve this issue. Any helps will appreciate

**Comment by yantijin** [comment]
Hi~, we didn't implemented the discrete form of subvpsde, so please set `training.continuous = True` in the config file.

**Comment by hanlaoshi** [comment]
OK, I got it. Thank you for your rapid response。 By the way, does the "ScoreGrad VP SDE" of the original paper correspond to 'ddpm_d' or 'ddpm_c' or just one of the best of them?

**Comment by yantijin** [comment]
VP SDE corresponds to `ddpm_c`, VE SDE corresponds to `smld_c`, the letter `d` in `ddpm_d` represents "discrete" while the `c` in `ddpm_c` represents "continue"

**Comment by hanlaoshi** [comment]
> 
So, all six datasets used the 'xxx_c' and subVPSDE. But for some count data, such as taxi, and wiki, those data also fitting continuous mode?

**Comment by hanlaoshi** [comment]
This is outstanding work that impresses me. I used the configuration of elec on the taxi data set, and the results are quite different from the original paper. Can you tell me which parameters are most important to adjust for different data sets?

**Comment by yantijin** [comment]
> > 
> 
> So, all six datasets used the 'xxx_c' and subVPSDE. But for some count data, such as taxi, and wiki, those data also fitting continuous mode?

Yes, all the datasets used in paper can be fit for ScoreGrad based on various SDEs.

**Comment by yantijin** [comment]
> This is outstanding work that impresses me. I used the configuration of elec on the taxi data set, and the results are quite different from the original paper. Can you tell me which parameters are most important to adjust for different data sets?

The config files for different datasets are different. There are some important hyperparameters. In the training process, you should pay more attention on num_scales, beta_min, beta_max, num_cells. In the sampling process, you should pay more attention on  the selection of predictor and corrector.

**Comment by yantijin** [comment]
> > 
> 
> So, all six datasets used the 'xxx_c' and subVPSDE. But for some count data, such as taxi, and wiki, those data also fitting continuous mode?

By the way, recently we added an conditional ODE sampler which requires only about 20 steps for sampling. The prediction speed can be significantly improved without performance degradation.

**Comment by hanlaoshi** [comment]
> > > 
> > 
> > 
> > So, all six datasets used the 'xxx_c' and subVPSDE. But for some count data, such as taxi, and wiki, those data also fitting continuous mode?
> 
> By the way, recently we added an conditional ODE sampler which requires only about 20 steps for sampling. The prediction speed can be significantly improved without performance degradation.

Congrats!! By the way, I did not find any publication information for this paper, so is the status of this paper still under review?
