### ISSUE TITLE
Error: Padding value causes wrapping around more than once.

### ISSUE THREAD

**Issue by GFHF114cx** [yantijin/ScoreGradPred#3]
Hey, error loading own data: Padding value causes wrapping around more than once.

Any help would be greatly appreciated

**Comment by yantijin** [comment]
Hi~, the data  loading module is based on PytorchTS and GluonTS instead of ScoreGrad. You can read the documentation of these two packages. The transformation of the data is in `create_transformation` of `score_sde_estimator.py`.
